version: '3.1'

services:

  foxxy:
    build:
      context: .
      dockerfile: Dockerfile_node
    command: /bin/bash -c "yarn && yarn start"
    ports:
      - 4001:4001
    volumes:
      - ./foxxy/:/workspace
      - node_modules:/workspace/node_modules
    depends_on:
      - arangodb
    links:
      - arangodb:arangodb
    networks:
      frontend:

  cms:
    build: .
    command: /bin/bash -c "cd /var/www && lapis server"
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www
      - arangodb-uploads:/var/www/static/uploads
    depends_on:
      - arangodb
      - foxxy
    links:
      - arangodb:arangodb
    networks:
      frontend:

  cms_prod:
    build: .
    restart: always
    command: /bin/bash -c "cd /var/www && moonc *.moon && moonc **/*.moon && lapis server production"
    ports:
      - 9090:80
    volumes:
      - ./:/var/www
      - arangodb-uploads:/var/www/static/uploads
    depends_on:
      - arangodb
    links:
      - arangodb:arangodb
    networks:
      frontend:

  arangodb:
    image: arangodb/arangodb:3.4.5
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: password
    networks:
      frontend:
        ipv4_address: 172.31.0.6
    ports:
      - 8530:8529
    volumes:
      - arangodb-data:/var/lib/arangodb3
      - arangodb-app:/var/lib/arangodb3-app
      - arangodb-uploads:/home
  e2e:
    image: cypress/base:10
    depends_on:
      - cms
    # note: inside e2e container, the network allows accessing
    # "web" host under name "web"
    # so "curl http://web" would return whatever the webserver
    # in the "web" container is cooking
    # see https://docs.docker.com/compose/networking/
    environment:
      - CYPRESS_baseUrl=http://cms
    command: npx cypress run
    # mount the host directory e2e/cypress and the file e2e/cypress.json as
    # volumes within the container
    # this means that:
    #  1. anything that Cypress writes to these folders (e.g., screenshots,
    #     videos) appears also on the Docker host's filesystem
    #  2. any change that the developer applies to Cypress files on the host
    #     machine immediately takes effect within the e2e container (no docker
    #     rebuild required).
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json
volumes:
  arangodb-data:
  arangodb-app:
  arangodb-uploads:
  node_modules:

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.31.0.0/24