version: 2.1
orbs:
  cypress: cypress-io/cypress@1.14.0

executors:
  fasty:
    docker:
      - image: solisoft/fasty
      - image: arangodb/arangodb:3.6.1
        environment:
          ARANGO_ROOT_PASSWORD: password
        command: [--server.endpoint=http+tcp://0.0.0.0:8530]
  with-chrome:
    docker:
      - image: 'cypress/browsers:chrome69'
jobs:
  build:
    executor:
      name: fasty
    steps:
      - run:
          name: 'Install foxxy'
          command: npm install -g foxxy && npm install -g foxx-cli
      - run:
          name: 'Add ~/.foxxrc'
          command: echo -e "[server.foxxy]\nurl=http://localhost:8530\nusername=root\npassword=\n\n[server.fasty]\nurl=http://localhost:8530\nusername=root\npassword=password" >> ~/.foxxrc
      - checkout
      - run: cp foxxy/app/js/config.js.sample foxxy/app/js/config.js
      - run:
          name: 'Edit nginx.conf'
          command: echo -e "\nuser root root;" >> nginx.conf
      - run:
          name: 'Prepare database'
          command: |
            echo 'db._createDatabase("db_demo");' | arangosh --server.endpoint=http+tcp://0.0.0.0:8530 --server.password password
            cd foxxy/
            foxxy upgrade settings --server fasty --database db_demo
            foxxy upgrade --server fasty --database db_demo
            cd ..

      - run:
          name: 'Moon'
          command: /bin/bash -c "moonc *.moon && moonc **/*.moon"

workflows:
  version: 2
  build:
    jobs:
      - build
      - cypress/run:
          requires:
            - build
          start: lapis server
          executor: with-chrome
          browser: chrome