version: 2.1
orbs:
  cypress: cypress-io/cypress@1.14.0

executors:
  fasty:
    docker:
      - image: solisoft/fasty
      - image: arangodb/arangodb:3.6.1
        environment:
          ARANGO_ROOT_PASSWORD: password
        command: [--server.endpoint=http+tcp://0.0.0.0:8530]
  with-chrome:
    docker:
      - image: solisoft/fasty
      - image: arangodb/arangodb:3.6.1
        environment:
          ARANGO_ROOT_PASSWORD: password
        command: [--server.endpoint=http+tcp://0.0.0.0:8530]
      - image: 'cypress/browsers:chrome69'
jobs:
  build:
    executor:
      name: fasty
    steps:

workflows:
  version: 2
  build:
    jobs:
      - build
      - cypress/run:
          requires:
            - build
          start: lapis server
          executor: with-chrome
          browser: chrome